# Generated by Django 6.0.5 on 2026-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_xp', models.IntegerField(default=0, verbose_name='XP ON')),
                ('ona_xp', models.IntegerField(default=0, verbose_name='XP ONA')),
            ],
        ),
    ]
