# Generated by Django 6.0.5 on 2026-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xp',
            name='on_lvl',
            field=models.IntegerField(default=1, verbose_name='LVL ON'),
        ),
        migrations.AddField(
            model_name='xp',
            name='ona_lvl',
            field=models.IntegerField(default=1, verbose_name='LVL ONA'),
        ),
    ]
