# Generated by Django 6.0.5 on 2026-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_xp_on_lvl_xp_ona_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='xp',
            name='on_xp_need',
            field=models.IntegerField(default=5, verbose_name='XP potřebné pro další level'),
        ),
        migrations.AddField(
            model_name='xp',
            name='ona_xp_need',
            field=models.IntegerField(default=5, verbose_name='XP potřebné pro další level'),
        ),
    ]
